name       : perl-date-calc
version    : 6.4
release    : 5
source     :
    - http://search.cpan.org/CPAN/authors/id/S/ST/STBEY/Date-Calc-6.4.tar.gz : 7ce137b2e797b7c0901f3adf1a05a19343356cd1f04676aa1c56a9f624f859ad
license    : Artistic-1.0-Perl
component  : programming.perl
summary    : This package provides all sorts of date calculations based on the Gregorian
    calendar.
description: |
    This package provides all sorts of date calculations based on the Gregorian calendar (the one used in all western countries today). The package is designed as an efficient (and fast) toolbox, not a bulky ready-made application. It provides extensive documentation and examples of use, multi-language support and special functions for business needs.
builddeps  :
    - perl-carp-clan
    - perl-bit-vector
rundeps    :
    - perl-carp-clan
    - perl-bit-vector
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
check      : |
    %perl_build test
